// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flirtify.Data;

#nullable disable

namespace service.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221221122436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("flirtify.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Geneder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KnownAs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Chad",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(410),
                            DateOfBirth = new DateTime(1970, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test1@gmail.com",
                            Geneder = "",
                            Interests = "Consectetur incididunt nostrud incididunt laborum enim exercitation.",
                            Introduction = "Tempor aute voluptate aliquip ea laborum irure minim exercitation sint fugiat consectetur minim amet occaecat. Quis sint irure minim sunt magna proident velit enim adipisicing dolor. Ullamco culpa pariatur et ex. Cupidatat fugiat culpa eiusmod officia id esse reprehenderit labore consectetur aliqua officia irure excepteur cillum. Tempor est quis sit officia qui sit tempor nulla id consectetur cupidatat exercitation.\r\n",
                            KnownAs = "Erin",
                            LastActive = new DateTime(2020, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Minim commodo excepteur aliqua elit excepteur cillum nostrud eiusmod elit tempor incididunt consectetur sint quis. Cillum eiusmod nulla ad tempor nostrud incididunt ut labore irure enim. Labore culpa culpa qui exercitation fugiat. Anim Lorem consectetur aliqua consectetur velit elit do ullamco id eiusmod non velit. Ea nostrud adipisicing dolor do labore minim reprehenderit amet nisi. Commodo magna elit elit adipisicing excepteur incididunt excepteur. Nulla ea magna culpa cupidatat tempor irure et mollit nostrud.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(460),
                            Username = "Erin"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Guyana",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(770),
                            DateOfBirth = new DateTime(1956, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@gmail.com",
                            Geneder = "",
                            Interests = "Pariatur nostrud fugiat anim est enim.",
                            Introduction = "Eiusmod aliquip amet aliqua labore excepteur est laborum qui mollit commodo proident. Lorem sint nulla in enim proident cillum velit dolore. Esse eu proident eiusmod sint culpa consequat et. Consectetur eiusmod sint incididunt minim dolor culpa. Irure incididunt reprehenderit ad occaecat reprehenderit commodo aute nulla eiusmod aute incididunt magna Lorem occaecat.\r\n",
                            KnownAs = "Claire",
                            LastActive = new DateTime(2020, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Aliqua ad aliquip ea labore. Dolore laborum consectetur ea excepteur velit minim Lorem et ad officia nisi mollit commodo. Exercitation consequat dolore elit adipisicing dolore ex deserunt do eiusmod consectetur ullamco ipsum non. Minim fugiat exercitation ipsum laborum quis qui consequat. Sint nulla adipisicing fugiat labore in esse ea in Lorem. Ex anim id exercitation non consequat officia commodo in ad minim et velit. Aliquip occaecat sit adipisicing magna.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(770),
                            Username = "Claire"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Latvia",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(840),
                            DateOfBirth = new DateTime(1985, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test3@gmail.com",
                            Geneder = "",
                            Interests = "Enim anim ullamco do duis est Lorem excepteur irure cillum laboris.",
                            Introduction = "Commodo veniam consectetur id anim nostrud proident sunt enim elit ut. Id ullamco anim eiusmod amet exercitation laboris nostrud quis tempor incididunt adipisicing commodo. Aliquip ex incididunt proident aliquip velit tempor tempor laboris anim in.\r\n",
                            KnownAs = "Allie",
                            LastActive = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Id sit pariatur ex consectetur adipisicing. Ut velit culpa labore nisi excepteur incididunt cillum reprehenderit dolore anim duis anim voluptate amet. Sint mollit exercitation laboris ex enim excepteur. Ea enim incididunt sit anim velit. Magna quis duis consequat deserunt qui ex sit velit.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(840),
                            Username = "Allie"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Angola",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(890),
                            DateOfBirth = new DateTime(1980, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test4@gmail.com",
                            Geneder = "",
                            Interests = "Laboris in ipsum nisi nostrud voluptate tempor sit voluptate nisi sint consequat velit ad incididunt.",
                            Introduction = "Veniam ex dolor velit est in est occaecat adipisicing ullamco in sunt fugiat. Commodo ullamco cillum voluptate pariatur anim est ad esse aliqua elit in non excepteur. Laboris sint sunt eiusmod eu incididunt proident duis. Ad et ad elit dolore aliquip aliquip cupidatat ut sunt do elit laboris. Mollit non officia aliqua excepteur culpa occaecat consectetur do fugiat aute mollit occaecat aliquip.\r\n",
                            KnownAs = "Lori",
                            LastActive = new DateTime(2020, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Culpa commodo dolore ea culpa aute. Consectetur aliqua mollit irure ea amet qui sunt aliquip anim. Laborum mollit et enim duis occaecat.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(890),
                            Username = "Lori"
                        },
                        new
                        {
                            Id = 5,
                            Country = "US Minor Outlying Islands",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(980),
                            DateOfBirth = new DateTime(1958, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test5@gmail.com",
                            Geneder = "",
                            Interests = "Irure mollit non amet sunt dolore aute mollit voluptate eu eu voluptate magna dolor.",
                            Introduction = "Eiusmod aliqua aliquip ut pariatur dolor duis eiusmod nulla exercitation ut. Lorem anim cillum tempor sunt do officia qui fugiat sint adipisicing laborum cillum. Quis sit in incididunt deserunt proident nisi fugiat do.\r\n",
                            KnownAs = "Vilma",
                            LastActive = new DateTime(2020, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Cillum tempor qui amet elit nisi incididunt sunt. Ullamco sint id quis aliqua consequat est ad commodo amet reprehenderit proident ex in enim. Dolore ad dolore ipsum sit deserunt magna. Est esse ipsum cupidatat commodo ea proident tempor proident ipsum mollit. Dolor do aliqua est ipsum et. Tempor officia minim commodo excepteur id et. Cillum aute commodo aliqua amet anim.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(980),
                            Username = "Vilma"
                        },
                        new
                        {
                            Id = 6,
                            Country = "France",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1030),
                            DateOfBirth = new DateTime(1992, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test6@gmail.com",
                            Geneder = "",
                            Interests = "Ut nisi ut id aliquip dolor elit esse amet duis id dolore labore officia ut.",
                            Introduction = "Laborum ad nulla ex in Lorem amet. Deserunt dolor excepteur nostrud laborum aliquip sunt qui est. Irure est labore laborum cillum aute in occaecat.\r\n",
                            KnownAs = "Marks",
                            LastActive = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Id exercitation amet ea proident laborum do ut adipisicing fugiat proident ullamco est esse deserunt. Irure sit et aliqua sunt ea duis pariatur minim magna voluptate reprehenderit exercitation occaecat id. Magna et ipsum amet minim pariatur ipsum aute laborum deserunt occaecat irure Lorem ipsum. Consequat aute magna excepteur culpa ea velit dolore ad et non consequat eiusmod amet nisi. Fugiat in proident veniam aute incididunt sint ipsum aute ea in id occaecat voluptate.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1030),
                            Username = "Marks"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Philippines",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1090),
                            DateOfBirth = new DateTime(1966, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test7@gmail.com",
                            Geneder = "",
                            Interests = "Laboris do Lorem nulla ea aute minim consectetur.",
                            Introduction = "Laboris esse aute pariatur culpa Lorem amet quis amet ex officia veniam ullamco. Aliquip adipisicing pariatur occaecat ad elit culpa sit quis ullamco ad sit. Qui eu incididunt anim excepteur aliqua culpa aliqua in quis occaecat sint. Incididunt reprehenderit in amet qui est sint.\r\n",
                            KnownAs = "Sampson",
                            LastActive = new DateTime(2020, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Occaecat ipsum officia proident irure aliqua cupidatat consequat consequat enim irure et voluptate consectetur consequat. Et Lorem ex voluptate consequat cupidatat nostrud magna ut sunt eiusmod. In ipsum sit dolor exercitation in labore esse laboris culpa dolore laboris. Aute aliqua ad ipsum proident magna deserunt est consectetur Lorem anim duis ut mollit incididunt.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1090),
                            Username = "Sampson"
                        },
                        new
                        {
                            Id = 8,
                            Country = "St. Pierre and Miquelon",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1140),
                            DateOfBirth = new DateTime(1987, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test8@gmail.com",
                            Geneder = "",
                            Interests = "Deserunt excepteur proident ea irure consectetur sint deserunt non nisi aliqua nostrud eu.",
                            Introduction = "Et anim eiusmod est enim laboris. Dolore laboris deserunt Lorem fugiat laboris nisi non. Ad velit proident qui incididunt ut. Occaecat nisi mollit tempor consectetur est. Adipisicing reprehenderit voluptate dolore magna sint dolor adipisicing ad esse in. Sint in fugiat mollit nostrud.\r\n",
                            KnownAs = "Forbes",
                            LastActive = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Voluptate ut ex eu qui nisi proident enim dolor culpa elit est esse fugiat. Ipsum dolore dolor elit deserunt pariatur consequat aliqua culpa magna. Irure sint ea ipsum irure nulla in. Ad deserunt id excepteur magna eiusmod est ex. Qui pariatur velit sint cillum mollit Lorem laboris cupidatat aliquip deserunt consectetur. Sit labore aute ullamco velit mollit cillum cillum consequat ut id occaecat cillum. Lorem sunt ut proident sint veniam non consequat ad est occaecat ut.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1140),
                            Username = "Forbes"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Barbados",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1200),
                            DateOfBirth = new DateTime(1983, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test9@gmail.com",
                            Geneder = "",
                            Interests = "Minim ullamco mollit sit cillum duis adipisicing labore consequat qui nostrud velit mollit.",
                            Introduction = "Dolore duis fugiat aliqua officia adipisicing ex ex mollit. Velit nulla excepteur officia id commodo voluptate occaecat reprehenderit in aliqua do occaecat. Nulla labore incididunt incididunt eiusmod Lorem eiusmod pariatur sint consectetur cupidatat duis. Ipsum veniam occaecat labore cupidatat fugiat ullamco eu cupidatat pariatur consectetur eiusmod do minim. Ea commodo nostrud cillum tempor ex anim qui Lorem officia. Eiusmod laboris nisi dolor amet reprehenderit amet voluptate non irure.\r\n",
                            KnownAs = "Carney",
                            LastActive = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Culpa deserunt mollit deserunt cupidatat commodo velit officia et nisi ad. Sint ea consequat qui do proident et velit aute. Incididunt aute sit elit consectetur ipsum id. Tempor adipisicing proident ipsum aute laborum incididunt veniam magna eiusmod.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1200),
                            Username = "Carney"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Afghanistan",
                            CreatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1250),
                            DateOfBirth = new DateTime(1996, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test10@gmail.com",
                            Geneder = "",
                            Interests = "Nisi non eu irure ex.",
                            Introduction = "Do dolor velit labore sint cupidatat pariatur. Duis ea Lorem adipisicing in magna non eiusmod mollit qui. Amet occaecat anim laborum nulla voluptate nulla aute duis in cupidatat duis officia. Aliquip quis qui mollit dolore nulla. Nisi dolore do dolor enim.\r\n",
                            KnownAs = "Wynn",
                            LastActive = new DateTime(2020, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Ullamco do enim sunt qui eiusmod. Incididunt do exercitation consectetur qui labore sint. Ad sit veniam dolore laborum sunt est esse aliquip. Duis excepteur ipsum laborum sunt duis sint dolor voluptate consectetur ad ea voluptate ad nostrud. Est mollit qui sit mollit dolor Lorem nisi sit et voluptate ut fugiat. Eu incididunt cillum do quis do labore velit ullamco pariatur ex anim laboris.\r\n",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 24, 35, 970, DateTimeKind.Local).AddTicks(1250),
                            Username = "Wynn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
